name: Build and Push Docker Image

on:
  push:
    # Trigger when pushing to the 'main' branch
    branches: [ "main" ]
    # Trigger only if Docker files change
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  workflow_dispatch: # Allows manual workflow launch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read     # Read repository code (necessary for checkout)
      packages: write    # Allow writing to the organization's registry (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Registry and Tags Configuration ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Registry and Image Name
        run: |
          echo "REGISTRY=ghcr.io" >> $GITHUB_ENV
          echo "IMAGE_NAME=review" >> $GITHUB_ENV

      # --- 1. Login to Registry ---
      - name: Log in to Registry (${{ env.REGISTRY }})
        uses: docker/login-action@v3
        with:
          # If GHCR
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} # Github user
          password: ${{ secrets.GITHUB_TOKEN }} # Native Github token (for GHCR)

      # --- 2. Build and Push Image ---
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Context is the root directory
          push: true
          # Define tags: latest AND a tag based on the short commit SHA
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}